database:
  name:     postgres
sqlite:
  driver:   sqlite3
  host:     localhost
  usuario:  root
  password: "123456"
  bd:       "../demo/northwindEF.db"
  debug:    false
postgres:
  driver:   postgres7
  host:     localhost
  usuario:  post
  password: post
  bd:       SIMA
  debug:    false
mysql:
  driver:   mysql
  host:     localhost
  usuario:  root
  password: root
  bd:       northwind
  debug:    false
