database:
  name:     sqlite
sqlite:
  driver:   sqlite3
  host:     localhost
  usuario:  root
  password: "123456"
  bd:       ../demofiles/northwindEF.db
  debug:    false
postgres:
  driver:   postgresql
  host:     localhost
  usuario:  postgres
  password: postgres
  bd:       northwind
  debug:    false
mysql:
  driver:   mysql
  host:     localhost
  usuario:  root
  password: root
  bd:       northwind
  debug:    false
